//src/pages/[slug].tsx
import { useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import LoginPage from "~/components/loginpage";
import { MacroSummary, MealForm, MealLog } from "~/components/meals";
import Navbar from "~/components/navbar";
import Image from "next/image";

const ProfilePage: NextPage = () => {
  const { user } = useUser();
  const [selectedDate, setSelectedDate] = useState(new Date());

  return (
    <>
      <Head>
        <title>Fitache</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image src = {user?.profileImageUrl || '/favicon.ico' } width={56} height={56} alt = "profile image" className = "rounded-full h-20 w-20"/>
      <main className="flex flex-col h-screen items-center justify-start">
        {/* Show Navbar if user is signed in */}
        {!!user && <Navbar />}
        {!!user && (
          <div className="mb-2 text-xl font-bold">
            Selected Date: {new Date(selectedDate.getTime() - selectedDate.getTimezoneOffset() * 60000).toISOString().slice(0, 10)}
          </div>
        )}
        
      </main>
    </>
  );
};

export default ProfilePage;