//src/pages/index.tsx
import { SignInButton, useUser, useClerk } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { MacroSummary, MealForm, MealLog } from "~/components/meals";



const Home: NextPage = () => {
  const user = useUser();
  const [selectedDate, setSelectedDate] = useState(new Date());
  const [key, setKey] = useState(Date.now());

  return (
    <>
      <Head>
        <title>Fitache</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center justify-center">
        <div className="mb-4 flex items-center justify-center">
          {!!user.isSignedIn && <MacroSummary selectedDate={selectedDate} />}
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
          {!!user.isSignedIn && (
            <DatePicker selected={selectedDate} onChange={(date: Date | null) => date && setSelectedDate(date)} />

          )}
         {!!user.isSignedIn && (
            <MealForm 
              selectedDate={selectedDate} 
              refetchMealLog={() => setKey(Date.now())} 
            />
          )}
          {!!user.isSignedIn && <MealLog selectedDate={selectedDate} key={key} />} 
        </div>
      </main>
    </>
  );
};

const SignOutButton = () => {
  const { signOut } = useClerk();

  const handleSignOut = () => {
    signOut().catch((error) => {
      console.error("Failed to sign out", error);
    });
  };

  return <button onClick={handleSignOut}>Sign out</button>;
};

export default Home;